In [1]:
from gymnasium.wrappers import TransformObservation
import numpy as np

from game.FindCarEnv import FindCarEnv
from game.GridGeneration import DisjointBlobs 
from game.wrappers import local_view_wrapper, one_hot_wrapper

In [2]:
obstacle_gen = DisjointBlobs(
    max_count=2,
    max_size=10,
)

In [8]:
env = FindCarEnv(width=10, height=6, num_fake_targets=2, render_mode="console", obstacle_scheme=obstacle_gen)
wrapper, obs_space = local_view_wrapper(env.observation_space, n=5)
env = TransformObservation(env, wrapper, obs_space)
wrapper, obs_space = one_hot_wrapper(env.observation_space)
env = TransformObservation(env, wrapper, obs_space)
print(np.moveaxis(env.reset(seed=42)[0], -1, 0))
#print(env.reset(seed=42))
env.render()

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [1 1 0 1 1]
  [1 1 1 1 1]
  [1 1 1 0 1]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 1 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 1 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
. . . . . . . A . . 
F . . . . . . . . . 
. . # . . . . . F . 
# # # . T . # . . . 
# # # . . . # # # . 
# # # . # # # # # # 



In [7]:
env.grid.shape

AttributeError: 'TransformObservation' object has no attribute 'grid'